name: acceptance-tests-latest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: build and vet the provider
        run: make
        env:
          GO111MODULE: on
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.3
          terraform_wrapper: false
      - name: run acceptance tests
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          TF_ACC: 1
          GO111MODULE: on
          SONAR_HOST: http://127.0.0.1:9000
          SONAR_USER: admin
          SONAR_PASS: admin
      - name: Run code coverage
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: codecov/codecov-action@v2
    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000